apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: tetragon
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: cilium-repo
      interval: 5m
  releaseName: tetragon
  values:
    tetragon:
      enableK8sAPI: true
      k8sApiServer:
        enabled: true
      export:
        enrichK8s: true
      exportAllowList: |-
        {"event_set":["PROCESS_EXEC", "PROCESS_EXIT", "PROCESS_KPROBE", "PROCESS_UPROBE", "PROCESS_TRACEPOINT"]}
      # We do include kube-system namespaces
      exportDenyList: |-
        {"health_check":true}
      #  {"namespace":["","kube-system"]}
      enableProcessCred: true
      # See process namespaces (linux ns that is)
      enableProcessNs: true
      prometheus:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "2112"
        serviceMonitor:
          enabled: true
          namespace: kube-system
          extraLabels:
            release: prometheus
          additionalLabels:
            release: prometheus
          endpoints:
            - port: metrics  # or http-metrics, depending on the service port name
              interval: 15s
              path: /metrics
              honorLabels: true
              relabelings:
                - sourceLabels: ['__meta_kubernetes_pod_node_name']
                  targetLabel: 'node'
                  action: 'replace'
                  replacement: '${1}'
                - sourceLabels: ['__meta_kubernetes_pod_name']
                  targetLabel: 'tetragon_pod'
                  action: 'replace'
                  replacement: '${1}'
    metrics:
      enabled: true
      port: 2112
      name: metrics