apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 66.3.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    grafana:
      enabled: false
    prometheus:
      prometheusSpec:
        scrapeConfigNamespaceSelector:
          matchLabels: {}  # empty matchLabels to match all namespaces
        serviceMonitorNamespaceSelector:
          matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: In
              values:
                - kube-system
                - monitoring
        serviceMonitorSelector:
          matchLabels:
            release: prometheus