apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-repo
      interval: 5m
  releaseName: ingress-nginx
  values:
    controller:
      ingressClassResource:
        default: true
      config:
        proxy-buffer-size: 128k
        proxy-buffers-number: 8